In [1]:
import random
import numpy as np
import sys

sys.path.append('/Users/davidlaredorazo/Documents/University_of_California/Research/Projects')

#Data handlers
from ann_framework.data_handlers.data_handler_Oscillator import OscillatorDataHandler

In [12]:
k = 1
c = 0.1
D = 1

sigma_x = np.sqrt(D / (k*c))
sigma_y = np.sqrt(D / c)

In [ ]:
input_x = []
input_y = []
output_p = []

for i in np.arange(2000):
    input_x.append(random.uniform(-10,10))
    input_y.append(random.uniform(-10,10))
    output_p.append( np.exp( - ( input_x[i]**2 / (2 * sigma_x**2) + input_y[i]**2 / (2*sigma_y**2) ) ) / (2*np.pi*sigma_x*sigma_y) )
#print(output_p)

In [ ]:
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

In [ ]:
fig = plt.figure()
ax = Axes3D(fig)
surf = Axes3D.scatter(ax, input_x, input_y, output_p)

In [21]:
def real_p(x1, x2, sigma_x, sigma_y):
    
    z = (x1**2)/(2 * sigma_x**2) + (x2**2)/(2*sigma_y**2)
    d = 2*np.pi*sigma_x*sigma_y
    
    p = np.exp( -z )/d
    
    return np.reshape(p, [p.shape[0], 1])

In [11]:
dhandler_stochastic = OscillatorDataHandler()

dhandler_stochastic.load_data(verbose=1, cross_validation_ratio=0.2, x=[0,0], boundaries=[5,5], n=[50,50])
dhandler_stochastic.print_data()


None
None
None
Loading data. Cros-Validation ratio 0.2
Printing shapes

Training data (X, y)
(7200, 2)
(7200, 1)
Cross-Validation data (X, y)
(1800, 2)
(1800, 1)
Testing data (X, y)
(1000, 2)
(1000, 1)
Printing first 5 elements

Training data (X, y)
[[-0.85858586 -2.47474747]
 [ 2.07070707 -4.19191919]
 [ 2.07070707  2.77777778]
 [-1.56565657  0.85858586]
 [-4.7979798   4.39393939]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Cross-Validation data (X, y)
[[ 2.77777778 -3.68686869]
 [-2.47474747 -0.15151515]
 [-1.16161616  2.37373737]
 [-2.57575758 -2.47474747]
 [-1.16161616  0.15151515]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Testing data (X, y)
[[ 1.76767677 -3.78787879]
 [ 1.06060606  1.76767677]
 [ 1.06060606  2.97979798]
 [-4.09090909  0.25252525]
 [ 1.26262626  1.86868687]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


/Users/davidlaredorazo/anaconda/envs/tensorflow/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2010: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [22]:
p = real_p(dhandler_stochastic.X_crossVal[:,0], dhandler_stochastic.X_crossVal[:,1], sigma_x, sigma_y)
print(p)
print(p.shape)

e = p - dhandler_stochastic.y_crossVal
print(e)
print(e.shape)

[[0.00548403]
 [0.01170395]
 [0.01122445]
 ...
 [0.01359784]
 [0.01078657]
 [0.0054173 ]]
(1800, 1)
[[0.00548403]
 [0.01170395]
 [0.01122445]
 ...
 [0.01359784]
 [0.01078657]
 [0.0054173 ]]
(1800, 1)
